### ISSUE TITLE
Is it possible to get the text from AS400 screen by providing from/to row/column/length?

### ISSUE THREAD

**Issue by MaryWX1118** [Blazemeter/RTEPlugin#14]
I got this additional question when I am trying to explore more ...
Is it possible to get/buffer the text from the screen by just providing from row/column/length?

say I have a scenario, as an operator, I am expected to create a ticket, and after the ticket is created successfully, in status bar session, I should be able to see the lines of message "A ticket number xxxxxx has been created successfully...".(this is an example only, there are many cases that we need to get those generated randomly by system and use them later.) I  will need to get this ticket number and buffer it to some variable and then I can use the variable later to do search ticket, update ticket actions, etc.

Thanks!
Mary

**Comment by Baraujo25** [comment]
Hello @MaryWX1118 ,

The plugin does not have that functionality for itself, but, thanks to JMeter we can extract certain parts of the response body (screen) using a Regular Expression Extractor.

Please refer to [this](https://github.com/Blazemeter/RTEPlugin/tree/v3.1#how-to-extract-a-value-on-the-screen-from-a-given-position) section, where is explained how to extract a part of the screen using a RegExExtractor. That part of the screen will be saved on a variable for later usage. 
It looks like suits perfect for your scenario.

As always, let me know if you have any inconvenience. 
I hope this helps you. I will be looking forward to your response.

Kind regards,
Joaquin.

**Comment by MaryWX1118** [comment]
Thanks Joaquin! I tried once just now, it works.

Issue closed.

**Comment by MaryWX1118** [comment]
Thanks Joaquin! I tried once this morning, it works.

Thanks!

Mary Wu

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
