### ISSUE TITLE
RTE for VT220

### ISSUE THREAD

**Issue by Awang1964** [Blazemeter/RTEPlugin#2]
Thank you for this plugin.
I am interested to see if VT220 terminal type support is planned or forthcoming?

**Comment by rabelenda** [comment]
Hello, we have it on the radar as something for the future but have no planned date for implementing it yet. Thank you for asking, and if anyone es is requiring support for this protocol, please comment or give some feedback in this issue so we are aware of the interest in such protocol for prioritization over other things we have on the backlog.

Regards.

**Comment by Awang1964** [comment]
Thanks for the quick response.
We do have an enterprise mission-critical application using VT220 protocol for which we have an existing performance testing solution.  However, support for the tool is being sunset.

**Comment by Baraujo25** [comment]
Hi @Awang1964 ,

The RTE-Plugin is now supporting the VT IBM protocols.
For this support, we have used a VT220 library as core. In the plugin options, you will find a VT420, but as far as we have experienced, your protocol should work as well. 

The VT protocol is not only supported for manual scripting, but it is also supported by the recorder.
Now you can just interact with your VT Mainframe Application as you normally do and, record every step for performance testing!

- New version available on [Plugins Manager](https://jmeter-plugins.org/install/Install/) as always.

- Additionally, if you like to install it manually, here are the steps:

  1. Go to [RTE-Plugin release v3.1](https://github.com/Blazemeter/RTEPlugin/releases/tag/v3.1)
  1. Download all the jar files on that release.
  1. Place the **jmeter-bzm-rte-3.1.jar** on your _JMETER_HOME/lib/ext_
  1. Place the other jars on _JMETER_HOME/lib_
  1. Run JMeter, enjoy your testing!

  **NOTE:** Make sure you do not have duplicated libraries. If that happens, the plugin will not work properly. I would recommend you to use a fresh new JMeter.

Please give it a try and let us know how it went!

Best regards,
Joaquin.

**Comment by Baraujo25** [comment]
Hi @Awang1964,

I'm closing this issue due to the inactivity.

If you have any issues while testing your VT220 terminal, feel free to open another issue!

Bests,
Joaquin.
