### ISSUE TITLE
Is the RTE Plugin exposed as a public maven artifact ?

### ISSUE THREAD

**Issue by rakeshjk** [Blazemeter/RTEPlugin#22]
Is the RTE Plugin exposed as a public maven artifact ?

https://mvnrepository.com/artifact/com.blazemeter
I am not able to find any dependency for Jmeter RTE plugin the mvn repository, can you please let me know the artifact id for this please.

**Comment by Baraujo25** [comment]
Hi @rakeshjk,

You are right the RTE Plugin is not exposed in Central Maven Repository. 

However I can provide you a work around using [JitPack](https://jitpack.io/) in order to plug it as a dependency in your project:
```xml
<project>
...
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>
...
<dependencies>
  <dependency>
      <groupId>com.github.blazemeter</groupId>
      <artifactId>RTEPlugin</artifactId>
      <version>3.2</version>
  </dependency>
  ...
</dependencies>
...
</project>
```
Let us know how it goes!

**Comment by rakeshjk** [comment]
Thank you for quick response, it is working now.

I Suggest better you expose this as public artifact, so that it will be using to many of them.
Really appreciate for a quick and prompt response

**Comment by rakeshjk** [comment]
Can you please make this as a central Central Maven Repository and share the dependency.
As in our test lab box is it not working due to firewire on https://jitpack.io

**Comment by Baraujo25** [comment]
I'm sorry to hear that. 

Can I ask you for the propuse of this? What would you actually need from RTE?

Maybe you don't need the whole plugin to achieve your goal.. It would be possible that you just need the libraries that the plugin is using ([dm3270](https://github.com/Blazemeter/dm3270), [xtn5250](https://github.com/Blazemeter/xtn5250) ← Has a built in emulator! or [jVT220](https://github.com/Blazemeter/jVT220))
